kind: Template
apiVersion: v1
metadata:
  name: aiops-globals
parameters:
- name: AWS_KEY
  required: true
- name: AWS_SECRET
  required: true
objects:

- kind: Secret
  apiVersion: v1
  labels:
    app: aiops-pipeline
  metadata:
    name: aiops-secrets
    type: Opaque
  stringData:
    aws_key: "${AWS_KEY}"
    aws_secret: "${AWS_SECRET}"
